#!/bin/bash
#PBS -N cos760_04
#PBS -l select=1:ncpus=24
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -V

# Load modules
module load intel/2019.4

# Change directory
cd ${PBS_O_WORKDIR}

# Make sure that the logs directory is created before running the job
mkdir -p ${HOME}/logs

# Run MPI code with 8 processes, 2 times in the background
for i in {2..3}; do
    mpirun -np 8 ./mpi data/tsplib/gr17.tsp ${HOME}/logs/mpi_t8_n1_r${i}.csv &
done

# Wait for all background processes to finish
wait