#!/bin/bash
#PBS -N cos760_07
#PBS -l select=1:ncpus=24
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -V

# Load modules
module load intel/2019.4

# Change directory
cd ${PBS_O_WORKDIR}

# Make sure that the logs directory is created before running the job
mkdir -p ${HOME}/logs

# Run MPI code with 16 processes, once in the background
mpirun -np 16 ./mpi data/tsplib/gr17.tsp ${HOME}/logs/mpi_t16_n1_r3 &

# Wait for all background processes to finish
wait