#!/bin/bash
#PBS -N cos760_09
#PBS -l select=1:ncpus=24
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -V

# Load modules
module load intel/2019.4

# Change directory
cd ${PBS_O_WORKDIR}

# Make sure that the logs directory is created before running the job
mkdir -p ${HOME}/logs

# Run OpenMP code with 16 threads once in the background
export OMP_NUM_THREADS=16
./openmp data/tsplib/gr17.tsp ${HOME}/logs/openmp_t16_n1_r2 &

# Wait for all background processes to finish
wait