#!/bin/bash
#PBS -N cos760_10
#PBS -l select=1:ncpus=48
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -V

# Load modules
module load intel/2019.4

# Change directory
cd ${PBS_O_WORKDIR}

# Make sure that the logs directory is created before running the job
mkdir -p ${HOME}/logs

# Run MPI code with 48 processes, once the background
mpirun -np 48 ./mpi data/tsplib/gr17.tsp ${HOME}/logs/log_mpi_48_procs_3.csv &

# Wait for all background processes to finish
wait